language: php

sudo: false

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer require phpunit/phpunit:${PHPUNIT}

script:
  - ./bin/phpunit

matrix:
  include:
      - php: 5.6
        env: PHPUNIT=~5.7
      - php: 7.0
        env: PHPUNIT=~5.7
      - php: 7.1
        env: PHPUNIT=~6
      - php: nightly
        env: PHPUNIT=~6
      - php: hhvm
        env: PHPUNIT=~5.7
